[tool.black]
line-length = 100
target-version = ["py311"]
exclude = [
  "venv",
  ".venv",
  "build",
  "dist",
  "__pycache__",
]

[tool.isort]
profile = "black"
line_length = 100
skip = ["venv", ".venv", "build", "dist", "__pycache__"]

